spring:
    application:
        name: plus

elasticsearch:
    host: https://localhost:9200
    port: 9200
    username: elastic
    password: changeme
    ssl:
        ca-path: ca.crt

management:
    endpoint:
        health:
            show-details: always